version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: taxcalc-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypasswor
      POSTGRES_DB: tax_residency_db
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
      target: development
    container_name: taxcalc-fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    environment:
      DB_TYPE: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tax_residency_db
      DB_USER: myuser
      DB_PASSWORD: mypasswor
    depends_on:
      - postgres

volumes:
  postgres_data:
